# DAWR BIE
- hosts: ag-bie
  roles:
    - common
    - java
    - webserver
    - tomcat
    - mysql-5.7
    - jenkins-simple
    - cas2
    - apikey
    - userdetails
    - bie-index
    - solr
    - biocache-properties
    - namedata
    - nameindex
    - process-config
    - nsl-dwca
    - taxxas-dwca
    - name-processing
    - ag-bie-jenkins-config
    - ag-bie-cas-config
    - bie-hub
  become: yes
